OAuth2/Models/TokenModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OAuth2.Models
{
    public class TokenModel
    {
        public string Token_Type { get; set; }
        public string Access_Token { get; set; }
        public int Expires_In { get; set; }
    }
}

OAuth2/Controllers/FacebookController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OAuth2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace OAuth2.Controllers
{
    public class FacebookController : Controller
    {
        private string appId = "2082285298464516";
        private string secret = "6d4b7fad8c3695100e32e7225d163b51";
        private string state = "TiSBK";
        private string redirectURI = "https://localhost:44307/Facebook/GetToken";
        private string baseURI = "https://graph.facebook.com/v2.11/";

        // GET: Facebook
        public ActionResult Login()
        {
            return Redirect($"https://www.facebook.com/v2.11/dialog/oauth?client_id={appId}&response_type=code&redirect_uri={redirectURI}&state={state}");
        }

        public ActionResult GetToken(string state, string code, string error_reason, string error, string error_description)
        {
            if (error == null)
            {
                HttpResponseMessage response;
                HttpClient client = new HttpClient() { BaseAddress = new Uri(baseURI + "oauth/") };

                response = client.GetAsync(client.BaseAddress + GetAccessToken(appId, redirectURI, secret, code)).Result;

                if (response.IsSuccessStatusCode)
                {
                    var jsonResponse = response.Content.ReadAsStringAsync().Result;
                    var tokenResponse = JsonConvert.DeserializeObject<TokenModel>(jsonResponse);

                    HttpContext.Session.Add("token", tokenResponse.Access_Token);
                    HttpContext.Session.Add("expires", tokenResponse.Expires_In);

                    return Redirect("https://localhost:44307/Facebook/ShowProfile");
                }
            }
            
            return Redirect("https://localhost:44307/Home/About");
        }

        private string GetAccessToken(string clientId, string redirectUri, string secret, string code)
        {
            return $"access_token?client_id={clientId}&redirect_uri={redirectUri}&client_secret={secret}&code={code}&scope=user_likes user_actions.news user_managed_groups pages_show_list";
        }

        public ActionResult ShowProfile()
        {
            string token = HttpContext.Session["token"].ToString();
            string results = "";
            
            HttpResponseMessage response;
            HttpClient client = new HttpClient() { BaseAddress = new Uri(baseURI) };

            response = client.GetAsync(client.BaseAddress + GetMyProfile(token)).Result;
            if (response.IsSuccessStatusCode)
            {
                var jsonResponse = response.Content.ReadAsStringAsync().Result;

                JObject deserializedResponse = JsonConvert.DeserializeObject(jsonResponse) as JObject;

                Dictionary<string, string> data = new Dictionary<string, string>();
                
                foreach (var item in deserializedResponse)
                {
                    data.Add(item.Key, item.Value.Value<string>());
                    ViewData[item.Key] = item.Value.Value<string>();
                }

                results += deserializedResponse.ToString().Trim();

                ViewData["Results"] = results;


                client = new HttpClient() { BaseAddress = new Uri(baseURI) };

                response = client.GetAsync(client.BaseAddress + GetMyPicture(token, data["id"])).Result;
                if (response.IsSuccessStatusCode)
                {
                    var jsonResponse2 = response.Content.ReadAsStringAsync().Result;

                    JObject deserializedResponse2 = JsonConvert.DeserializeObject(jsonResponse2) as JObject;

                    data.Add("photoUrl", deserializedResponse2["data"]["url"].ToString());
                    ViewData["photoUrl"] = deserializedResponse2["data"]["url"].ToString();

                    client = new HttpClient() { BaseAddress = new Uri(baseURI) };

                    response = client.GetAsync(client.BaseAddress + GetMyCover(token, data["id"])).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var jsonResponse3 = response.Content.ReadAsStringAsync().Result;

                        JObject deserializedResponse3 = JsonConvert.DeserializeObject(jsonResponse3) as JObject;

                        data.Add("cover", deserializedResponse3["cover"]["source"].ToString());
                        ViewData["cover"] = deserializedResponse3["cover"]["source"].ToString();

                        return View();
                    }

                    return Redirect("https://localhost:44307/Home/About");
                }

                return Redirect("https://localhost:44307/Home/About");
            }

            return Redirect("https://localhost:44307/Home/About");
        }

        private static string GetMyProfile(string token)
        {
            return $"me?access_token={token}";
        }

        private static string GetMyPicture(string token, string id)
        {
            return $"{id}/picture?redirect=false&type=large&access_token={token}";
        }

        private static string GetMyCover(string token, string id)
        {
            return $"{id}?fields=cover&access_token={token}";
        }
    }
}

OAuth2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OAuth2.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Login()
        {
            // https://www.facebook.com/v2.11/dialog/oauth?client_id={FacebookAppId}&response_type=code&redirect_uri={RedirectURI}&state={State}


            return null;
        }
    }
}

OAuth2/Views/Facebook/ShowProfile.cshtml
@{
    ViewBag.Title = "ShowProfile";
}

<img src="@ViewData["cover"].ToString()" />

<h2>Witaj @ViewData["name"].ToString()</h2>
<img src="@ViewData["photoUrl"].ToString()" />

<p>Twój identyfikator to: @ViewData["id"].ToString();</p>

OAuth2/Views/Home/About.cshtml
@{
    ViewBag.Title = "ERROR";
}
<h2>@ViewBag.Title.</h2>
@*<h3>@ViewBag.Message</h3>*@

<p>ERROR.</p>

OAuth2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OAuth2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

OAuth2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Log in", "Login", "Facebook")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>